services:
  rocketmq-namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-namesrv-test
    networks:
      - rocketmq-net
    ports:
      - 9886:9876
    command: sh mqnamesrv
    volumes:
      - ./rocketmq/namesrv/logs:/home/rocketmq/logs
      - ./rocketmq/namesrv/store:/home/rocketmq/store

  rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-broker-test
    networks:
      - rocketmq-net
    ports:
      - 11909:10909
      - 11911:10911
      - 11912:10912
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
    volumes:
      - ./rocketmq/broker/logs:/home/rocketmq/logs
      - ./rocketmq/broker/store:/home/rocketmq/store
      - ./rocketmq/timerwheel:/home/rocketmq/timerwheel
      - ./rocketmq/broker/conf/broker.conf:/home/rocketmq/rocketmq-5.3.2/conf/broker.conf
      - ./rocketmq/broker/conf/plain_acl.yml:/home/rocketmq/rocketmq-5.3.2/conf/plain_acl.yml
    depends_on:
      - rocketmq-namesrv
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf
  rocketmq-proxy:
    image: apache/rocketmq:5.3.2
    container_name: rocketmq-proxy-test
    networks:
      - rocketmq-net
    depends_on:
      - rocketmq-broker
      - rocketmq-namesrv
    ports:
      - 8182:8080
      - 8181:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
    command: sh mqproxy

networks:
  rocketmq-net:
    driver: bridge