luohuo:
  swagger:
    license: Powered By zuihou
    licenseUrl: https://github.com/qianqian
    termsOfServiceUrl: https://github.com/qianqian
    version: '@project.version@'
    contact: # 联系人信息
      url: https://github.com/qianqian
      name: qianqian
      email: xxxxxx@qq.com
    global-operation-parameters: # 全局参数
      - name: Token
        description: 用户信息
        modelRef: String
        parameterType: header
        required: true
        # 默认值只是方便本地开发时，少填参数，生产环境请禁用swagger或者禁用默认参数
        defaultValue: "Bearer xxx"
      - name: Authorization
        description: 客户端信息
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "bGFtcF93ZWI6bGFtcF93ZWJfc2VjcmV0"
      - name: ApplicationId
        description: 应用ID
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "1"


# knife4j 文档通用配置 详情看: Knife4jProperties
knife4j:
  enable: true
  # 生产屏蔽文档
  production: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    #     是否在每个Debug调试栏后显示刷新变量按钮,默认不显示
    enableReloadCacheParameter: true
    #    是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
    enableVersion: true
    #    针对RequestMapping的接口请求类型,在不指定参数类型的情况下,如果不过滤,默认会显示7个类型的接口地址参数,如果开启此配置,默认展示一个Post类型的接口地址
    enableFilterMultipartApis: false
    #    是否开启动态参数调试功能
    enableDynamicParameter: true
    #    是否显示Footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2025 [luohuo-cloud](https://github.com/qianqian)

springdoc:
  # 默认是false，需要设置为true
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: ${knife4j.enable}
  api-docs:
    enabled: ${knife4j.enable}
    path: /v3/api-docs
  group-configs:
    # @luohuo.generator auto insert springdoc.groupconfigs
    - group: 'oauth_auth'
      displayName: 'oauth'
      paths-to-match: '/**'
      packages-to-scan: com.luohuo.flex.oauth
    - group: 'base_base'
      displayName: 'base-基础模块'
      paths-to-match: '/**'
      packages-to-scan: com.luohuo.flex.base
    - group: 'base_file'
      paths-to-match: '/**'
      displayName: 'base-文件模块'
      packages-to-scan: com.luohuo.flex.file
    - group: 'base_msg'
      paths-to-match: '/**'
      displayName: 'base-消息模块'
      packages-to-scan:
        - com.luohuo.flex.msg
        - com.luohuo.flex.sms
    - group: 'system'
      displayName: 'system'
      paths-to-match: '/**'
      packages-to-scan: com.luohuo.flex.system.controller
    - group: 'generator'
      displayName: 'generator'
      paths-to-match: '/**'
      packages-to-scan:
        - com.luohuo.flex.generator
        - com.luohuo.flex.test.controller

